name: CI
on: push
jobs:
  formatting-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2

      - name: Restore node_modules cache
        id: cache-npm
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: npm-${{ env.cache-name }}-
            npm-

      - name: "Install npm dependencies"
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: "Code formatting with Prettier"
        run: npm run prettier

      - name: "JS Docs"
        run: npm run generate-docs

      - name: "ESlint"
        run: npm run lint
      
      - name: "E2E + Unit Tests"
        run: npx serve source &; npm run test dailyLog; killall -9 node

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "" # If blank, default: triggered branch
          destination_branch: "main" # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: ":crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          pr_label: "auto-pr"
          github_token: ${{ secrets.GITHUB_TOKEN }}
